#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config window_gap           7

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config focused_border_color "#ccccff"
bspc config normal_border_color "#1f222b"
bspc config border_width 2
bspc config borderless_monocle true

bspc config active_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"

bspc config top_padding -6
bspc config bottom_padding -2

#keyboard
setxkbmap -layout us,ru -option grp:alt_shift_toggle
xset r rate 175 40

#rules
bspc rule -a kitty desktop='^1' follow=on
bspc rule -a qutebrowser desktop='^2' follow=on
bspc rule -a vesktop desktop='^3' follow=on
bspc rule -a sudo bash ~/zapret-discord-youtube-linux/main_script.sh -nointeractive desktop='^10' follow=on
#autostart
killall sxhkd
sxhkd &

killall picom
picom --config $HOME/.config/picom/picom.conf &

killall feh
feh --bg-scale wallpapers/everlasting_summer/остановка-день.jpg &

killall polybar
polybar &

