#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config window_gap           7

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config focused_border_color "#ffffff"
bspc config normal_border_color "#1f222b"
bspc config border_width 5
bspc config borderless_monocle true

bspc config active_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"

#keyboard
setxkbmap -layout us,ru -option grp:alt_shift_toggle

#autostart
#killall sxhkd &
sxhkd &

killall picom
picom --config $HOME/.config/picom/picom.conf &

killall nitrogen
nitrogen --restore &

killall dunst
dunst &

killall polybar
polybar &

